# It is not obvious how YML translates to TOML. But it is extremely straightforward.

# example: WINDOW, COLORS, etc. are tables, and should be represented as [window], [colors], respectively.
# specifics of variables go under them. e.g.- look under "dynamic_padding" under-
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#window
# write `dynamic_padding = true` (without backticks -`) under the table [window]
# for variables with multiple values, use "dotted keys". Like setting `padding.x = 5` under [window].

# The TOML homepage (https://toml.io/en/v1.0.0) was very helpful in figuring this out. 

# default config: https://github.com/TwiggieSmallz/Default-Alacritty-TOML-Config/blob/main/alacritty.toml

[window]

opacity = 1.0

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"


[font]
size = 12.0
builtin_box_drawing = true

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[shell]
program = "/usr/bin/fish"
# args = ["-l"]

[scrolling]
history = 10000
multiplier = 3

[bell]
animation = "Linear"
duration = 0

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true
thickness = 0.15

# Tip: for inspiration, look for values in the source code files of your favorite VS Code themes, and use the color picker in
# Google to test colors before setting a value, or simply using an editor such as VS Code where colors are displayed in a 
# small box when a HEX is detected by the editor.
