format = """
 $all 
"""
right_format = """$time"""# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = false
# style_user = "bg:#9A348E"
# style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
# [os]
# style = "bg:#9A348E"
# disabled = true # Disabled by default

[directory]
# style= "fg:#6A8AEA"
truncation_length = 4
truncate_to_repo = true
fish_style_pwd_dir_length = 3
# truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " 󰧮 "
"Music" = "  "
"Movies" = " 󰿏 "
"Pictures" =  " "
"Sources" = "  "
"Downloads" = "  "
"~" = "  "
"/" = "  "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[line_break]
disabled = true # leave as TRUE  

[character]
success_symbol = " [󰁔]() "
# error_symbol =   " [ ](fg:#d56767)[ ](fg:#d56767) "
error_symbol =   " [ ]()[ ]() "
format = "$symbol"
disabled = false


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~     LANGUAGES     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
[java]
disabled = false
symbol = "•  "
format = '[${symbol}]($style)'
style = "fg:#a48989"

[python]
disabled = false
pyenv_version_name= false
python_binary = 'python'
format = '[${symbol}(\($virtualenv\))]($style)'
style = "fg:#a48989"
symbol = "• 󱔎 "

[lua]
disabled = false
symbol = "• "
format = '[${symbol}]($style)'
style = "fg:#a48989"

[nodejs]
disabled = false
symbol = "• 󰎙 "
format = '[${symbol}]($style)'
style = "fg:#a48989"

[package]
disabled = false
symbol = "•  "
display_private = false
format = '[${symbol}]($style)'
style = "fg:#a48989"

[docker_context]
disabled = false
symbol = "•  "
only_with_files = true
format = '[${symbol}]($style)'
style = "fg:#a48989"

[golang]
disabled = false
symbol = "•  "
format = '[${symbol}]($style)'
style = "fg:#a48989"

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'


[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'


[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'


[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'



# ~~~~~~~~~~~~~~~~~~~~~~~~~~~ GIT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
[git_branch]
disabled = false
symbol = " "
style = "fg:#b79999"
truncation_length = 5   # length == ABCDE
format = '[$symbol$branch(:$remote_branch)]($style) ' # this sets path ../../../../

[git_commit]
disabled = false
commit_hash_length = 1

[git_state]
disabled = false
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = " picking"
bisect = "bisecting"
am = "am'ing"
am_or_rebase = "am/rebase"

[git_status]
disabled = false
style= "fg:#5F8575"
stashed = " ${count} "
ahead = "󰞙 ${count} "
behind = "󰞒 ${count} "
diverged = "󰵉 ${ahead_count} ${behind_count} "
conflicted = " ${count} "
deleted = " ${count} "
renamed = " ${count} "
modified = " ${count} "
staged = " ${count} "
untracked = "󱅘 ${count}"
