[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" },
]
reveal = [
  { run = 'xdg-open "$(dirname "$0")"', for = "linux" },
]
play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" },
]

[open]
prepend_rules = [
  { name = "*.md", use = "edit" },
  { name = "*.json", use = "edit" },
  { name = "*.toml", use = "edit" },
  { name = "*.yaml", use = "edit" },
  { name = "*.yml", use = "edit" },
  { name = "*.kdl", use = "edit" },
  { name = "*.lua", use = "edit" },
  { name = "*.fish", use = "edit" },
  { name = "*.sh", use = "edit" },
]
